name: "steer"
# Version is the version of Helm plus the number of official builds for this
# plugin
version: "2.4.1+0"
usage: "operates multiple charts in a cluster"
description: "Help operate multiple charts in a cluster."
command: "$HELM_PLUGIN_DIR/steer"
useTunnel: true
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
